{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hypha-k8s-worker.fullname" . }}
  labels:
    {{- include "hypha-k8s-worker.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hypha-k8s-worker.fullname" . }}
  labels:
    {{- include "hypha-k8s-worker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hypha-k8s-worker.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hypha-k8s-worker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
